version: '3'
services:
  user-service:
    build:
      context: ./User-Service-API
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    networks:
      - app-network
    environment:
      APP_NAME: ${APP_NAME}
      PORT: 3001
      NODE_ENV: ${NODE_ENV}
      APP_VERSION: ${APP_VERSION}
      LOG: ${LOG:-true}
      DRIVE_DISK: ${DRIVE_DISK:-local}
      PG_HOST: ${PG_HOST}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB_NAME: ${PG_DB_NAME}

  product-service:
    build:
      context: ./Products-Service-API
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    environment:
      APP_NAME: ${APP_NAME}
      PORT: 3002
      NODE_ENV: ${NODE_ENV}
      APP_VERSION: ${APP_VERSION}
      LOG: ${LOG:-true}
      DRIVE_DISK: ${DRIVE_DISK:-local}
      PG_HOST: ${PG_HOST}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB_NAME: ${PG_DB_NAME}

  cart-service:
    build:
      context: ./Cart-Service-API
      dockerfile: Dockerfile
    ports:
      - '3003:3003'
    networks:
      - app-network
    environment:
      APP_NAME: ${APP_NAME}
      PORT: 3003
      NODE_ENV: ${NODE_ENV}
      APP_VERSION: ${APP_VERSION}
      LOG: ${LOG:-true}
      DRIVE_DISK: ${DRIVE_DISK:-local}
      PG_HOST: ${PG_HOST}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB_NAME: ${PG_DB_NAME}

  order-service:
    build:
      context: ./Order-Service-API
      dockerfile: Dockerfile
    ports:
      - '3004:3004'
    networks:
      - app-network
    environment:
      APP_NAME: ${APP_NAME}
      PORT: 3004
      NODE_ENV: ${NODE_ENV}
      APP_VERSION: ${APP_VERSION}
      LOG: ${LOG:-true}
      DRIVE_DISK: ${DRIVE_DISK:-local}
      PG_HOST: ${PG_HOST}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB_NAME: ${PG_DB_NAME}

  pos-middle-ware-service:
    build:
      context: ./Pos-Middle-Ware-Service
      dockerfile: Dockerfile
    ports:
      - '3005:3005'
    networks:
      - app-network
    environment:
      APP_NAME: ${APP_NAME}
      PORT: 3005
      NODE_ENV: ${NODE_ENV}
      APP_VERSION: ${APP_VERSION}
      LOG: ${LOG:-true}
      DRIVE_DISK: ${DRIVE_DISK:-local}
      PG_HOST: ${PG_HOST}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB_NAME: ${PG_DB_NAME}
      ORDER_SERVICE_URL: http://order-service:3004
      CART_SERVICE_URL: http://cart-service:3003 # adjust port as needed

networks:
  app-network:
    driver: bridge
